plugins {
    id 'com.android.library' version '8.6.1'
}

android {
    namespace 'org.godotengine.godot.stubs'
    compileSdk 35

    defaultConfig {
        minSdk 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            java.srcDirs = ['java']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}
