version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Kyiv'
    open-pull-requests-limit: 5
    reviewers:
      - 'Averixor'
    groups:
      npm-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:15'
      timezone: 'Europe/Kyiv'
    open-pull-requests-limit: 5
    reviewers:
      - 'Averixor'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'gradle'
    directory: '/android'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:30'
      timezone: 'Europe/Kyiv'
    open-pull-requests-limit: 5
    reviewers:
      - 'Averixor'
    groups:
      android-dependencies:
        patterns:
          - '*'