plugins {
    id 'com.android.library' version '8.6.1'
}

android {
    namespace 'com.averixor.lostnumber.firebase'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 36
        consumerProguardFiles 'proguard-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly files('../../build/libs/release/godot-lib.template_release.aar')
    implementation platform('com.google.firebase:firebase-bom:34.17.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'androidx.credentials:credentials:1.3.0'
    implementation 'androidx.credentials:credentials-play-services-auth:1.3.0'
    implementation 'com.google.android.libraries.identity.googleid:googleid:1.1.1'
}
