#!/usr/bin/env node
/**
 * Writes js/system/build-flags.generated.js (cheatsEnabled true/false).
 * Usage: node scripts/build-flags.mjs release|debug-cheats
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const mode = (process.argv[2] || 'release').trim();

if (mode !== 'release' && mode !== 'debug-cheats') {
  console.error(`Unknown build flags mode: ${mode}. Use "release" or "debug-cheats".`);
  process.exit(1);
}

const cheatsEnabled = mode === 'debug-cheats';
const outDir = join(root, 'js/system');
const outFile = join(outDir, 'build-flags.generated.js');

mkdirSync(outDir, { recursive: true });

const content =
  '/** Generated by scripts/build-flags.mjs — do not edit manually. */\n' +
  `window.LN_BUILD_FLAGS = { cheatsEnabled: ${cheatsEnabled} };\n`;

writeFileSync(outFile, content, 'utf8');
console.log(`Wrote ${outFile} (cheatsEnabled=${cheatsEnabled})`);
